### ISSUE TITLE
[Enhancement] option to set hostname in installer

### ISSUE THREAD

**Issue by aquifolly** [snowflakelinux/os-installer-snowflake-config#1]

**Comment by ahoneybun** [comment]
@vlinkz I believe this would need to be filed on the [OS-Installer page](https://gitlab.gnome.org/p3732/os-installer) correct?

**Comment by vlinkz** [comment]
Yeah, but also working on a new installer that has the feature

**Comment by aquifolly** [comment]
Closing due to https://github.com/snowflakelinux/icicle
